version: "3.8"
services:
  php:
    image: php:8.3.0-apache
    container_name: php83
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    build:
      context: .
      dockerfile: dockerfile
  db:
    image: mysql:8.0
    container_name: mysql80
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: my-secret
      MYSQL_DATABASE: Banque
      MYSQL_USER: salman
      MYSQL_PASSWORD: pass
    ports:
      - "3630:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: my-secret
      UPLOAD_LIMIT: 20M
    ports:
      - "8990:80"